# Questão 5 - Lista 1 - Inteligência Artificial

## a) Estime o vetor média e a matriz de covariância de cada distribuição gaussiana multivariada.

### Importação da biblioteca do Python para manipulação de vetores

In [ ]:
import numpy as np

### Declarando os vetores
Considera-se cw1 a classe w1 e cw2 a classe w2

In [ ]:
x1_cw1 = [-5.01, -5.43, 1.08, 0.86, -2.67, 4.94, -2.51, -2.25, 5.56, 1.03]
x2_cw1 = [-8.12, -3.48, -5.52, -3.78, 0.63, 3.29, 2.09, -2.13, 2.86, -3.33]

x1_cw2 = [-0.91, 1.3, -7.75, -5.47, 6.14, 3.6, 5.37, 7.18, -7.39, -7.5]
x2_cw2 = [-0.18, -2.06, -4.54, 0.5, 5.72, 1.26, -4.63, 1.46, 1.17, -6.32]

### Calculando os vetores média

$\mu_{w1} = 
\begin{bmatrix}
\mu_{x1\_w1}\\ 
\mu_{x2\_w1}
\end{bmatrix}$

$\mu_{w2} = 
\begin{bmatrix}
\mu_{x1\_w2}\\ 
\mu_{x2\_w2}
\end{bmatrix}$

In [ ]:
media_x1_cw1 = round(np.mean(x1_cw1), 3)
media_x2_cw1 = round(np.mean(x2_cw1), 3)
media_x1_cw2 = round(np.mean(x1_cw2), 3)
media_x2_cw2 = round(np.mean(x2_cw2), 3)

### Calculando as matrizes de covariância

$\sigma_{w1} = \begin{bmatrix}
s_{11\_w1} & s_{12\_w1} \\
s_{21\_w1} & s_{22\_w1}
\end{bmatrix}$ 

$\sigma_{w2} = \begin{bmatrix}
s_{11\_w2} & s_{12\_w2} \\
s_{21\_w2} & s_{22\_w2}
\end{bmatrix}$ 

In [ ]:
s11_w1 = 0
s12_w1 = 0
s21_w1 = 0
s22_w1 = 0
for i in range(0,10):
  s11_w1 += (x1_cw1[i]-media_x1_cw1)*(x1_cw1[i]-media_x1_cw1)
  s12_w1 += (x1_cw1[i]-media_x1_cw1)*(x2_cw1[i]-media_x2_cw1)
  s21_w1 += (x2_cw1[i]-media_x2_cw1)*(x1_cw1[i]-media_x1_cw1)
  s22_w1 += (x2_cw1[i]-media_x2_cw1)*(x2_cw1[i]-media_x2_cw1)

s11_w1 = round(s11_w1/9, 3)
s12_w1 = round(s12_w1/9, 3)
s21_w1 = round(s21_w1/9, 3)
s22_w1 = round(s22_w1/9, 3)

matriz_w1 = [[s11_w1, s12_w1], [s21_w1, s22_w1]]
matriz_w1

[[14.381, 7.695], [7.695, 14.623]]

In [ ]:
s11_w2 = 0
s12_w2 = 0
s21_w2 = 0
s22_w2 = 0
for i in range(0,10):
  s11_w2 += (x1_cw2[i]-media_x1_cw2)*(x1_cw2[i]-media_x1_cw2)
  s12_w2 += (x1_cw2[i]-media_x1_cw2)*(x2_cw2[i]-media_x2_cw2)
  s21_w2 += (x2_cw2[i]-media_x2_cw2)*(x1_cw2[i]-media_x1_cw2)
  s22_w2 += (x2_cw2[i]-media_x2_cw2)*(x2_cw2[i]-media_x2_cw2)

s11_w2 = round(s11_w2/9, 3)
s12_w2 = round(s12_w2/9, 3)
s21_w2 = round(s21_w2/9, 3)
s22_w2 = round(s22_w2/9, 3)

matriz_w2 = [[s11_w2, s12_w2], [s21_w2, s22_w2]]
matriz_w2

[[36.829, 9.981], [9.981, 13.169]]

## b) Determine a superfície de decisão

### Organizando os vetores e matriz de g1 e g2

In [ ]:
media_w1 = np.asarray([
    [media_x1_cw1],
    [media_x2_cw1]
], dtype='float32')

media_w2 = np.asarray([
    [media_x1_cw2],
    [media_x2_cw2]
], dtype='float32')

cov_w1 = np.asarray([
    [s11_w1, s12_w1],
    [s21_w1, s22_w1]
], dtype='float32')

cov_w2 = np.asarray([
    [s11_w2, s12_w2],
    [s21_w2, s22_w2]
], dtype='float32')

print(media_w1)
print(media_w2)
print(cov_w1)
print(cov_w2)

[[-0.44 ]
 [-1.749]]
[[-0.543]
 [-0.762]]
[[14.381  7.695]
 [ 7.695 14.623]]
[[36.829  9.981]
 [ 9.981 13.169]]


### Definindo a função discriminante g1

In [ ]:
def g1(x):
  termo1 = np.transpose(x-media_w1)
  termo2 = np.linalg.inv(cov_w1)
  termo3 = x-media_w1
  termo4 = np.dot(termo1, termo2)
  termo5 = np.dot(termo4, termo3)
  termo6 = np.log(np.linalg.det(cov_w1))
  resultado = float(-0.5*termo5 - 0.5*termo6)
  return round(resultado, 4)

### Definindo a função discriminante g2

In [ ]:
def g2(x):
  termo1 = np.transpose(x-media_w2)
  termo2 = np.linalg.inv(cov_w2)
  termo3 = x-media_w2
  termo4 = np.dot(termo1, termo2)
  termo5 = np.dot(termo4, termo3)
  termo6 = np.log(np.linalg.det(cov_w2))
  resultado = float(-0.5*termo5 - 0.5*termo6)
  return round(resultado, 4)

### Definindo a superfície de decisão g: g1-g2=0

In [ ]:
def g(x):
  termo1_1 = np.transpose(x-media_w1)
  termo2_1 = np.linalg.inv(cov_w1)
  termo3_1 = x-media_w1
  termo4_1 = np.dot(termo1_1, termo2_1)
  termo5_1 = np.dot(termo4_1, termo3_1)
  termo6_1 = np.log(np.linalg.det(cov_w1))

  termo1_2 = np.transpose(x-media_w2)
  termo2_2 = np.linalg.inv(cov_w2)
  termo3_2 = x-media_w2
  termo4_2 = np.dot(termo1_2, termo2_2)
  termo5_2 = np.dot(termo4_2, termo3_2)
  termo6_2 = np.log(np.linalg.det(cov_w2))

  resultado = float(-0.5*termo5_1 - 0.5*termo6_1 + 0.5*termo5_2 + 0.5*termo6_2)
  return resultado

## c) Classifique os pontos (padrões) (1, 2)t , (5, 3)t , (0, 0)t , (1, 0)t , decidindo pela classe com maior valor das funções discriminantes, isto e, max{gi(x)} ou faça pela região definida pela superfície de separação (função descriminante)


### Classificação do ponto (1,2)t -> Classe w1

In [ ]:
#Ponto (1,2)
ponto1 = np.asarray([
    [1,2]
], dtype='float32')
ponto1 = np.transpose(ponto1)
print(g1(ponto1))
print(g2(ponto1))

-3.0032
-3.2719


### Classificação do ponto (5,3t) -> Classe w2

In [ ]:
#Ponto (5,3)
ponto2 = np.asarray([
    [5,3]
], dtype='float32')
ponto2 = np.transpose(ponto2)
print(g1(ponto2))
print(g2(ponto2))

-3.6986
-3.6383


### Classificação do ponto (0,0)t -> Classe w1

In [ ]:
#Ponto (0,0)
ponto3 = np.asarray([
    [0,0]
], dtype='float32')
ponto3 = np.transpose(ponto3)
print(g1(ponto3))
print(g2(ponto3))

-2.6247
-2.9992


### Classificação do ponto (1,0)t -> Classe w1

In [ ]:
#Ponto (1,0)
ponto4 = np.asarray([
    [1,0]
], dtype='float32')
ponto4 = np.transpose(ponto4)
print(g1(ponto4))
print(g2(ponto4))

-2.6266
-3.0151
